### PR TITLE
Show lock owner in tooltip

### PR DESCRIPTION
**Pull request by juliushaertl**
Implements #7

### CODE REVIEW

**Comment by juliushaertl** [comment]
> In the menu it then says in the entry "Unlock" and in a subline: "Locked 16m ago by Frank" so people have context.

Not possible with the current file actions API. We can just set the label itself, but that doesn't look good imo: 
image

> The unlock entry could then have the avatar of the person instead of the lock as icon.

I don't think that would be a good solution as just showing an avatar gives no idea that the avatar is actually about locking.

How about this:
image
- On click we show the contacts menu
- Locking/unlocking will be performed though the 3-dots menu as it is currently

**Comment by jancborchardt** [comment]
> Not possible with the current file actions API. We can just set the label itself, but that doesn't look good imo:

Is it possible to add a second action, so a second line? Also because for a locked file, a lot of the actions like move, rename, etc should probably be disabled anyway, right?

**Comment by juliushaertl** [comment]
> Is it possible to add a second action, so a second line?

Yes it would look like this:
image

How would that integrate the contacts menu then? Having another popover on top of the existing one doesn't seem nice to me. 

> Also because for a locked file, a lot of the actions like move, rename, etc should probably be disabled anyway, right?

Not possible as far as I can see right now. We cannot disable the core file actions from outside of their apps javascript context.

**Comment by jancborchardt** [comment]
@juliushaertl screenshot seems good! :+1: Can we get the time as well, like "Locked by admin 4 min ago"?

Or what do you think?


> How would that integrate the contacts menu then? Having another popover on top of the existing one doesn't seem nice to me.

We do have that in the header Contacts menu as well – having a menu inside a popover is just something we will likely have, and it’s fine. In any case, it’s a different discussion?

**Comment by jancborchardt** [comment]
cc @daita @karlitschek also for reference and review

**Comment by karlitschek** [comment]
super cool. I agree that the time would be very good no know

**Comment by karlitschek** [comment]
@juliushaertl @rullzer @daita Can we merge that?

**Comment by rullzer** [comment]
Lets be practical here. Merge this as it is already a nice improvement and get it out. And then for the next version we add the tooltip with text. Small PRs are good PRs ;)

**Comment by juliushaertl** [comment]
Polished up a bit, ready to review from my side:

image

**Comment by jancborchardt** [comment]
If the entries are switched around then it’s good to go!

So you have: "Locked by Roeland" and then the action "Unlock file"

**Comment by juliushaertl** [comment]
Order is changed as well.

**Comment by rullzer** [comment]
@daita can you give this a go as well and merge?

**Comment by daita** [comment]
tested and all, thanks @juliushaertl

**Comment by rullzer** [comment]
Ah mmm so it does :boom: on the context menu. Because if a file is not locked the displayname is undefined. Which in turn breaks the sort.

**Comment by rullzer** [comment]
https://github.com/nextcloud/files_lock/pull/12/files#diff-d8804ee2bfb753a4105404489eded466R68-R75

There to be exact

**Pull request merged**
